apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "webcounter.fullname" . }}
  labels:
    app: {{ template "webcounter.name" . }}
    chart: {{ template "webcounter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "webcounter.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "webcounter.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.secret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          imagePullSecrets:
          - name: {{ .Values.image.secret }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: biab-dev-config
                key: biab.dev.host1
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
